services:
  db1:
    hostname: db1
    extends:
      file: ./docker-compose-db-template.yml
      service: db-template
    configs:
      - source: init-primary.sh
        target: /docker-entrypoint-initdb.d/init-primary.sh
    ports: ["5432:5432"]
  db2:
    hostname: db2
    extends:
      file: ./docker-compose-db-template.yml
      service: db-template
    configs:
      - source: init-replica.sh
        target: /docker-entrypoint-initdb.d/init-replica.sh
    ports: ["5433:5432"]
  db3:
    hostname: db3
    extends:
      file: ./docker-compose-db-template.yml
      service: db-template
    configs:
      - source: init-replica.sh
        target: /docker-entrypoint-initdb.d/init-replica.sh
    ports: ["5434:5432"]
  db4:
    hostname: db4
    extends:
      file: ./docker-compose-db-template.yml
      service: db-template
    configs:
      - source: init-replica.sh
        target: /docker-entrypoint-initdb.d/init-replica.sh
    ports: ["5435:5432"]
  pgcat1:
    hostname: pgcat1
    build: ..
    command: ["pgcat", "/pgcat.toml"]
    configs:
      - source: pgcat.toml
        target: /pgcat.toml
    ports: ["6432:6432", "9930:9930"]
  pgcat2:
    profiles:
      - ha
    hostname: pgcat2
    build: ..
    command: ["pgcat", "/pgcat.toml"]
    configs:
      - source: pgcat.toml
        target: /pgcat.toml
    ports: ["6433:6432", "9931:9930"]
  haproxy:
    profiles:
      - ha
    image: haproxy:3.0
    command: ["haproxy", "-f", "/haproxy.conf"]
    configs:
      - source: haproxy.conf
        target: /haproxy.conf
    ports: ["7432:6432"]
configs:
  pgcat.toml:
    file: ./pgcat.toml
  postgresql.conf:
    file: ./postgresql.conf
  init-primary.sh:
    file: ./init-primary.sh
  init-replica.sh:
    file: ./init-replica.sh
  haproxy.conf:
    file: ./haproxy.conf
