# POC config version 2:
# - use same pool for reads and writes
# - rely on pgcat's query parser read/write splitting feature
# - do not use pgcat sharding feature

# database backend consists of one primary and 3 replicas (PRRs).

# We need following capabilities:
#   Load balancing: Distribute traffic across all nodes.
#   Failover: when one of hosts fail, redirect traffic immediately.

[general]
host = "0.0.0.0"
port = 6432
admin_username = "pgcat"
admin_password = "pgcat"

# prometheus exporter is not enabled by default contrary to docs
enable_prometheus_exporter = true
prometheus_exporter_port = 9930

# adjust timeouts
ban_time = 30                             # 30 s; default: 60 s
connect_timeout = 2500                    # 2.5 s; default: 5 s
idle_timeout = 15000                      # 15 s; default: 30 s
server_lifetime = 43200000                # 12 h; default: 24 h
idle_client_in_transaction_timeout = 7200 # 2 h; default: not set
shutdown_timeout = 30000                  # 30 s; default: 60 s

# Enable TCP keepalives (default ???)
tcp_keepalives_idle = 5
tcp_keepalives_count = 5
tcp_keepalives_interval = 5

# Enable DNS cache to avoid slowdown when using DNS names to reach servers
dns_cache_enabled = true # default: false
dns_max_ttl = 30         # 30 s; default: 30 s

[pools.app1_read]
pool_mode = "transaction"
load_balancing_mode = "random"
default_role = "replica"
query_parser_enabled = false
query_parser_read_write_splitting = false
primary_reads_enabled = true
[pools.app1_read.shards.0]
database = "clickup"
servers = [
  [ "db1", 5432, "replica", ],
  [ "db2", 5432, "replica", ],
  [ "db3", 5432, "replica", ],
]
[pools.app1_read.users.0]
username = "app1_read"
password = "app1_read"
pool_size = 800

[pools.app1_write]
pool_mode = "transaction"
load_balancing_mode = "random"
default_role = "primary"
query_parser_enabled = false
query_parser_read_write_splitting = false
primary_reads_enabled = true
[pools.app1_write.shards.0]
database = "clickup"
servers = [
  [ "db1", 5432, "primary", ],
  [ "db2", 5432, "replica", ],
  [ "db3", 5432, "replica", ],
]
[pools.app1_write.users.0]
username = "app1_write"
password = "app1_write"
pool_size = 40
