# POC config version 1:
# - use separate R/W and R/O pools (one pool for each user)
# - do not rely on pgcat query parsing feature
# - do not use pgcat sharding feature

# database backend consists of one primary and 3 replicas (PRRs).

# We create one R/W pool and one R/O pool. Both pools contain _all_ 4 hosts.

# We need following capabilities:
#   Load balancing: Distribute traffic across all nodes.
#   Failover: when one of hosts fail, redirect traffic immediately.

[general]
host = "0.0.0.0"
port = 6432
admin_username = "pgcat"
admin_password = "pgcat"

# adjust timeouts
connect_timeout = 2500  # 2.5 s; default: 5 s
idle_timeout = 15000  # 15 s; default: 30 s
server_lifetime = 43200000  # 12 h; default: 24 h
idle_client_in_transaction_timeout = 7200  # 2 h; default: not set
shutdown_timeout = 30000  # 30 s; default: 60 s

# Enable DNS cache to avoid slowdown when using DNS names to reach servers
dns_cache_enabled = true  # default: false
dns_max_ttl = 30  # 30 s; default: 30 s

[pools.app1_read]
pool_mode = "transaction"
load_balancing_mode = "random"  # "random" or "loc"; default: "random"
default_role = "replica" # any/replica/primary; default: "any"
query_parser_enabled = false  # default: true

[pools.app1_read.users.0]
username = "app1_read"
password = "app1_read"
pool_size = 50

[pools.app1_read.shards.0]
database = "clickup"
servers = [
  ["db1", 5432, "replica"],
  ["db2", 5432, "replica"],
  ["db3", 5432, "replica"],
]

[pools.app1_write]
pool_mode = "transaction"
load_balancing_mode = "random"
default_role = "primary" # any/replica/primary; default: "any"
query_parser_enabled = false  # default: true

[pools.app1_write.users.0]
username = "app1_write"
password = "app1_write"
pool_size = 10

[pools.app1_write.shards.0]
# Note: you can specify only one primary, otherwise you get ERROR ThreadId(01) pgcat::config: Shard clickup has more than one primary configured
database = "clickup"
servers = [
  ["db1", 5432, "primary"],
  ["db2", 5432, "replica"],
  ["db3", 5432, "replica"],
]
